### ISSUE TITLE
cannot install from melpa due to dependency on notify-2010.8.20

### ISSUE THREAD

**Issue by milkypostman** [NicolasPetton/org-gnome.el#1]
see milkypostman/melpa#2824

an easy solution is to change the dependency to be something installable by melpa without the need for an additional package archive.

**Comment by NicolasPetton** [comment]
Donald Curtis writes:

> see milkypostman/melpa#2824
> 
> an easy solution is to change the dependency to be something
> installable by melpa without the need for an additional package
> archive.

Thanks, I'll replace it with the alert package.

> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/NicolasPetton/org-gnome.el/issues/1

## 

Nicolas Petton
http://nicolas-petton.fr
